<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <CurrentDotNetRuntimeVersion>net10.0</CurrentDotNetRuntimeVersion>
    <TargetFramework>$(CurrentDotNetRuntimeVersion)</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>codelocal</AssemblyName>
    <RootNamespace>CodeLocal</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>0.1.0</Version>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.56.0" />
  </ItemGroup>

</Project>
